pr 在评论添加 集成支持
linuxdeepin/.github pull request #518
Opened 2023-04-28 06:30 UTC by hudeng-go

用法 ：

- `/integrate`    该评论触发合并前的集成流程，会向集成项目自动创建并关联pr
- `/integrate milestone [topic]` 添加milestone以及topic参数支持，其中topic参数用于多个项目一起提交集成，方便多个项目合并前的集成操作，该支持在具体使用中还有待优化和完善

2023-04-28 06:40 UTC, hudeng-go commented
/review @asterwyx

2023-04-28 07:11 UTC, BLumia commented
没太懂这个的主要作用。是为某个项目的已合入的 PR 自动创建集成请求的 PR 的吗？是否可以展开介绍一下？

> 需要帮忙添加INTEGRATION_APP_ID和INTEGRATION_APP_PRIVATE_KEY两个secrets

已添加

> 各个项目的call-chatOps.yml文件需要调整，最好是批量调整一下。

linuxdeepin/.github 下的 call-chatOps.yml 更新后应该会触发批量自动更新。细节可以和 @myml 确认。

2023-04-28 07:28 UTC, hudeng-go commented
> 没太懂这个的主要作用。是为某个项目的已合入的 PR 自动创建集成请求的 PR 的吗？是否可以展开介绍一下？
> 
> > 需要帮忙添加INTEGRATION_APP_ID和INTEGRATION_APP_PRIVATE_KEY两个secrets
> 
> 已添加
> 
> > 各个项目的call-chatOps.yml文件需要调整，最好是批量调整一下。
> 
> linuxdeepin/.github 下的 call-chatOps.yml 更新后应该会触发批量自动更新。细节可以和 @myml 确认。

类似dtk项目，提交了修改代码的pr，可以在pr合并前评论`/integrate`就会自动修改integration.yml然后走集成流程，在testing测试通过后在合并pr，可以原有集成流程的基础上简化开发人员操作，同时可以一定程度上避免在集成阶段频繁的修改changelog和打tag。 如果这个过程执行得比较顺畅的化，可以考虑上集成阶段的lock branch吧？ 
![2aaae5f2-0be2-49d4-b82b-779d6d622184](https://user-images.githubusercontent.com/69233028/235082948-2591740d-d678-4b87-95fc-9ed7034e99b3.png)

2023-05-06 10:13 UTC, hudeng-go commented
@zccrs

2023-05-08 01:45 UTC, zccrs commented
> @zccrs

看不懂呀，没法帮你review

2023-05-08 01:47 UTC, myml commented
没注意之前的邮件，我看看

2023-05-08 02:07 UTC, myml requested changes

2023-05-08 02:07 UTC, myml commented on .github/workflows/chatOps.yml
> +      - name: Get integration app token
这个流程返回的是pr的hash吧？并不是什么app token

2023-05-08 02:07 UTC, myml commented on .github/workflows/auto-integration-pr.yml
> +              const response = await github.rest.issues.listComments({
最好加个per_page: 100, 默认是返回30条可能会出现问题

2023-05-08 02:07 UTC, myml commented on .github/workflows/auto-integration-pr.yml
> +        with:
这段加些注释吧，有些地方看不懂😅

2023-05-08 03:23 UTC, hudeng-go commented
> > @zccrs
> 
> 看不懂呀，没法帮你review

sweat_smile

2023-05-08 08:12 UTC, myml requested changes

2023-05-08 08:12 UTC, myml commented on .github/workflows/call-chatOps.yml
由于.github仓库的权限太大了，这个仓库不要加chatOps,避免因chatOps漏洞,让人随意合并代码

2023-05-08 08:12 UTC, myml commented on .github/workflows/auto-integration-pr.yml
>          with:
我说的加注释是说整段代码，并不是这一行

2023-05-09 07:29 UTC, myml approved these changes

2023-05-09 08:02 UTC, hudeng-go commented
/merge

2023-05-09 08:06 UTC, merged